#!/usr/bin/env python3
"""`PreToolUse` guard: an `Edit`/`Write`/`MultiEdit` about to touch a
generated surface -- `.claude/agents/sdd-*.md` (plus its manifest) or
anything under `.claude/skills/` -- by the harness' own edit tools, never a
versioned materializer script (local, temporary layer, same status as
`guard_bash_spec_writes.py`).

What it does
------------
Reads the `PreToolUse` payload Claude Code delivers on stdin (`session_id`,
`cwd`, `hook_event_name`, `tool_name`, `tool_input`), looks at
`tool_input.file_path` (`tool_input.notebook_path` too, in case a future
matcher reuses this hook for `NotebookEdit`) and denies exactly two surfaces:

1. `.claude/agents/sdd-*.md` or `.claude/agents/.claude-agents-manifest.yaml`
   -- generated by `scripts/materialize_claude_agents.py` from
   `.agents/agents/<rol>.md` (frontmatter without `model`/`effort`) fused
   with `.spec/perfiles.yaml`.
2. Anything under `.claude/skills/` -- generated by
   `scripts/materialize_claude_skills.py` from `.agents/skills/`.
3. Anything under `.claude/commands/` -- generated by
   `scripts/materialize_claude_commands.py` from `.agents/commands/`.

The canonical sources -- `.agents/agents/*.md`, `.agents/skills/**`,
`.agents/commands/**` and any other path -- pass through untouched: this hook
matches only the generated mirrors above, never their sources.

On a block it emits the `deny` decision on **stdout** and appends one JSONL
line to `.spec/.usage/guard-rejections-pre-edit.jsonl`. The rejection message
names the surface and the materializer that is the only allowed route to
change it.

Exit codes
----------
`EXIT_OK` (0), always -- same convention as `guard_bash_spec_writes.py`: the
decision travels as JSON on stdout, never as an exit code, so the shell
wrapper of `.claude/settings.json` can end in `|| true` without losing the
denial.

Fail-open: any exception of this hook's own (malformed JSON on stdin
included) is written to `.spec/.usage/guard-failures.log` and the tool is
**not** blocked.

No network, no file reads beyond the payload on stdin: stdlib only.
"""

from __future__ import annotations

import contextlib
import datetime
import json
import re
import sys
import traceback
from pathlib import Path

sys.dont_write_bytecode = True

#: `<repo>` by self-location -- same base as `guard_bash_spec_writes.py` and
#: as `usage/paths.py::default_repo_root` -- not `cwd` of the payload, not
#: `CLAUDE_PROJECT_DIR`.
REPO_ROOT = Path(__file__).resolve().parents[2]

USAGE_DIR = REPO_ROOT / ".spec" / ".usage"
REJECTIONS_LOG = USAGE_DIR / "guard-rejections-pre-edit.jsonl"
FAILURES_LOG = USAGE_DIR / "guard-failures.log"

#: Only exit code this hook ever uses.
EXIT_OK = 0

#: The two generated mirrors this guard protects, repo-relative, no leading
#: slash, forward slashes only.
_AGENTS_MIRROR = re.compile(
    r"(?:^|/)\.claude/agents/(?:sdd-[\w.-]*\.md|\.claude-agents-manifest\.yaml)$"
)
_SKILLS_MIRROR = re.compile(r"(?:^|/)\.claude/skills/")
_COMMANDS_MIRROR = re.compile(r"(?:^|/)\.claude/commands/")

#: (surface id) -> (allowed route, named in the denial message).
ROUTES = {
    "agents": "scripts/materialize_claude_agents.py",
    "skills": "scripts/materialize_claude_skills.py",
    "commands": "scripts/materialize_claude_commands.py",
}


def _now() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _append(path: Path, line: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(line + "\n")


def _log_failure(message: str) -> None:
    """Every failure of this hook's own leaves a motive here and blocks
    nothing. Never raises."""
    with contextlib.suppress(OSError):
        _append(FAILURES_LOG, f"{_now()} guard_generated_paths: {message}")


def normalize(raw: str) -> str:
    """`raw` (whatever shape the payload gives -- absolute under `REPO_ROOT`,
    `./`-prefixed, already relative) as a repo-relative, forward-slash path."""
    text = raw.strip().strip("'\"")
    if not text:
        return ""
    text = text.replace("\\", "/")
    path = Path(text)
    if path.is_absolute():
        try:
            return path.resolve().relative_to(REPO_ROOT).as_posix()
        except ValueError:
            return text.lstrip("/")
    if text.startswith("./"):
        text = text[2:]
    return text


def matched_surface(rel_path: str) -> str | None:
    """`"agents"`, `"skills"`, `"commands"`, or `None` when `rel_path` matches
    no generated mirror."""
    if not rel_path:
        return None
    if _AGENTS_MIRROR.search(rel_path):
        return "agents"
    if _SKILLS_MIRROR.search(rel_path):
        return "skills"
    if _COMMANDS_MIRROR.search(rel_path):
        return "commands"
    return None


def deny_reason(surface: str, rel_path: str) -> str:
    """Names the surface and the materializer that is the allowed route."""
    return (
        f"`{rel_path}` es una superficie generada -- no se edita a mano. "
        f"Vía permitida: `{ROUTES[surface]}`."
    )


def main() -> int:
    raw_stdin = sys.stdin.read()
    payload = json.loads(raw_stdin) if raw_stdin.strip() else {}
    if not isinstance(payload, dict):
        return EXIT_OK

    tool_input = payload.get("tool_input") or {}
    if not isinstance(tool_input, dict):
        return EXIT_OK

    raw_path = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not raw_path:
        return EXIT_OK

    rel_path = normalize(str(raw_path))
    surface = matched_surface(rel_path)
    if surface is None:
        return EXIT_OK

    reason = deny_reason(surface, rel_path)
    _append(
        REJECTIONS_LOG,
        json.dumps(
            {
                "ts": _now(),
                "session_id": payload.get("session_id", ""),
                "tool": payload.get("tool_name", ""),
                "path": rel_path,
                "surface": surface,
            },
            ensure_ascii=False,
        ),
    )
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            },
            ensure_ascii=False,
        )
    )
    return EXIT_OK


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:  # fail-open, the only broad catch of this file
        _log_failure(traceback.format_exc().replace("\n", " | "))
        sys.exit(EXIT_OK)
